apiVersion: apps/v1
kind: Deployment
metadata:
  name: mason-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mason-pod
  template:
    metadata:
      labels:
        app: mason-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - containerPort: 80
      volumes:
      - name: config
        configMap:
            name: mason-config
