apiVersion: v1
kind: Service
metadata:
  name: web-application
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: simple-webapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
